'use strict';
/*
 * Enrichment audit (pre-generation gate).
 *
 * 1. Reports indexable vs noindex page counts (by type).
 * 2. Takes the INDEXABLE worst-offenders (uniqueness < THRESHOLD) and splits
 *    them into:
 *       List A — pages WITH real stored local data to ground generation
 *       List B — pages THIN/empty on real local data (do NOT fabricate;
 *                candidates for noindex / consolidation instead)
 * 3. Sequences List A so the 3 contractors' service-area pages come first.
 *
 * Output: enrichment-audit.md + console summary. No content is generated.
 *
 * Usage: node scripts/enrichment-audit.js [thresholdPercent]   (default 50)
 */

const fs = require('fs');
const path = require('path');
const { scanPages, CONTRACTORS } = require('./contentScan');

const THRESHOLD = Number(process.argv[2] || 50);
const OUT = path.join(__dirname, '..', 'enrichment-audit.md');

const { pages } = scanPages();
const fmt = (n) => n === null ? 'n/a' : n.toFixed(1) + '%';

// ---- 1. indexable vs noindex, by type --------------------------------------
const types = ['city-hub', 'county-animal', 'city-animal'];
const idxTable = {};
for (const t of types) {
  const tp = pages.filter(p => p.type === t);
  idxTable[t] = {
    total: tp.length,
    indexable: tp.filter(p => p.indexable).length,
    noindex: tp.filter(p => !p.indexable).length,
  };
}
const allIndexable = pages.filter(p => p.indexable);

// ---- 2. indexable worst-offenders ------------------------------------------
const worst = allIndexable
  .filter(p => p.uniqueness !== null && p.uniqueness < THRESHOLD)
  .sort((a, b) => a.uniqueness - b.uniqueness);

// rich vs thin grounding (only city-hub/city-animal carry city signals;
// county-animal has no city-level signals so is treated as "needs review").
function ground(p) {
  if (p.type === 'county-animal') return { rich: p.signals.rich, note: p.signals.rich ? 'county-level grounding' : 'thin county data' };
  return { rich: p.signals.rich, note: p.hasCityHub === false ? 'no city-hub record' : '' };
}
const listA = []; // rich -> grounded generation
const listB = []; // thin -> noindex/consolidation decision
for (const p of worst) {
  (ground(p).rich ? listA : listB).push(p);
}

// sequence List A: contractor-covered first, then by worst uniqueness
const contractorRank = (p) => p.contractorCovered ? 0 : 1;
listA.sort((a, b) => contractorRank(a) - contractorRank(b)
  || (a.contractor || '').localeCompare(b.contractor || '')
  || a.uniqueness - b.uniqueness);
listB.sort((a, b) => a.uniqueness - b.uniqueness);

// ---- report ----------------------------------------------------------------
const sigStr = (p) => `nb:${p.signals.neighborhoods} geo:${p.signals.geographic_features} era:${p.signals.housing_era ? 'y' : 'n'}`;

let md = '';
md += '# Enrichment Audit — pre-generation gate\n\n';
md += `_Generated by \`scripts/enrichment-audit.js\`. Worst-offender threshold: uniqueness < **${THRESHOLD}%**. Nothing has been generated. Indexability mirrors \`server.js\` + \`data/permanentlyIndexed.json\` exactly. Contractor coverage is used only to SEQUENCE work — it has no effect on indexability._\n\n`;

md += '## 1. Indexable vs noindex (all scanned pages)\n\n';
md += '| Type | Total | Indexable | Noindex |\n|---|---|---|---|\n';
let tT = 0, tI = 0, tN = 0;
for (const t of types) {
  const r = idxTable[t]; tT += r.total; tI += r.indexable; tN += r.noindex;
  md += `| ${t} | ${r.total} | ${r.indexable} | ${r.noindex} |\n`;
}
md += `| **all** | **${tT}** | **${tI}** | **${tN}** |\n\n`;
md += `Only the **${tI} indexable** pages are enrichment candidates; the ${tN} noindex pages are not served to Google and are out of scope.\n\n`;

md += `## 2. Indexable worst-offenders (uniqueness < ${THRESHOLD}%)\n\n`;
md += `Found **${worst.length}** indexable pages below ${THRESHOLD}% uniqueness. Split by grounding data:\n\n`;
md += `- **List A (enrich — has real local data):** ${listA.length}\n`;
md += `- **List B (do NOT fabricate — noindex/consolidate decision):** ${listB.length}\n\n`;

// contractor breakdown of List A
md += '### Contractor coverage of List A (enrichment sequence)\n\n';
md += '| Order group | Contractor | Pages in List A |\n|---|---|---|\n';
const byContractor = {};
for (const p of listA) { const k = p.contractor || '(no contractor)'; byContractor[k] = (byContractor[k] || 0) + 1; }
let gi = 1;
for (const name of [...Object.keys(CONTRACTORS), '(no contractor)']) {
  if (byContractor[name]) md += `| ${name === '(no contractor)' ? '—' : gi++} | ${name} | ${byContractor[name]} |\n`;
}
md += '\n';

md += '### List A — pages to enrich (grounded generation), in work order\n\n';
md += '| # | Uniq | Words | Contractor | Local signals | URL |\n|---|---|---|---|---|---|\n';
listA.forEach((p, i) => {
  md += `| ${i + 1} | ${fmt(p.uniqueness)} | ${p.totalWords} | ${p.contractor || '—'} | ${sigStr(p)} | \`${p.url}\` |\n`;
});
md += '\n';

md += '### List B — thin on local data (NO fabrication — recommend noindex or consolidation)\n\n';
md += 'These indexable pages lack enough stored local facts to ground unique prose truthfully. Recommended action per page is **noindex** (drop from index until real local content exists) or **consolidate** (fold into the county-animal hub / city hub). Your decision.\n\n';
md += '| # | Uniq | Words | Contractor | Local signals | Why thin | URL |\n|---|---|---|---|---|---|---|\n';
listB.forEach((p, i) => {
  md += `| ${i + 1} | ${fmt(p.uniqueness)} | ${p.totalWords} | ${p.contractor || '—'} | ${sigStr(p)} | ${ground(p).note || 'thin signals'} | \`${p.url}\` |\n`;
});
md += '\n';

fs.writeFileSync(OUT, md, 'utf8');

// ---- console ---------------------------------------------------------------
console.log('=== Enrichment audit (threshold < ' + THRESHOLD + '% uniqueness) ===\n');
console.log('Indexable vs noindex:');
for (const t of types) console.log(`  ${t.padEnd(14)} total ${String(idxTable[t].total).padStart(4)}  indexable ${String(idxTable[t].indexable).padStart(4)}  noindex ${String(idxTable[t].noindex).padStart(4)}`);
console.log(`  ${'ALL'.padEnd(14)} total ${String(tT).padStart(4)}  indexable ${String(tI).padStart(4)}  noindex ${String(tN).padStart(4)}\n`);
console.log(`Indexable worst-offenders (< ${THRESHOLD}%): ${worst.length}`);
console.log(`  List A (enrich, has local data): ${listA.length}`);
console.log(`  List B (thin -> noindex/consolidate): ${listB.length}\n`);
console.log('List A contractor sequence:');
for (const name of [...Object.keys(CONTRACTORS), '(no contractor)']) if (byContractor[name]) console.log(`  ${String(byContractor[name]).padStart(3)}  ${name}`);
console.log('\nList A top of queue:');
listA.slice(0, 12).forEach((p, i) => console.log(`  ${String(i + 1).padStart(2)}. ${fmt(p.uniqueness).padStart(6)}  [${p.contractor || '—'}] ${p.url}`));
console.log('\nReport written to:', OUT);
